// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc.proto
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace RPCClient {
  public static partial class RPC
  {
    static readonly string __ServiceName = "RPCPkg.RPC";

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::RPCClient.Coords> __Marshaller_Coords = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::RPCClient.Coords.Parser.ParseFrom);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::RPCClient.Coords> __Method_GetCoord = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::RPCClient.Coords>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCoord",
        __Marshaller_Empty,
        __Marshaller_Coords);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::RPCClient.RpcReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of RPC</summary>
    public abstract partial class RPCBase
    {
      public virtual global::System.Threading.Tasks.Task<global::RPCClient.Coords> GetCoord(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for RPC</summary>
    public partial class RPCClient : grpc::ClientBase<RPCClient>
    {
      /// <summary>Creates a new client for RPC</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public RPCClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for RPC that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public RPCClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected RPCClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected RPCClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::RPCClient.Coords GetCoord(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetCoord(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::RPCClient.Coords GetCoord(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCoord, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::RPCClient.Coords> GetCoordAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetCoordAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::RPCClient.Coords> GetCoordAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCoord, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override RPCClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new RPCClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(RPCBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GetCoord, serviceImpl.GetCoord).Build();
    }

  }
}
#endregion
